sudo: required
language: generic
services: docker
script:
- docker pull dxjoke/tectonic-docker
- docker run --mount src=$TRAVIS_BUILD_DIR/documents,target=/usr/src/tex,type=bind
  dxjoke/tectonic-docker /bin/sh -c "tectonic --keep-intermediates --reruns 0 srs.tex"
deploy:
  provider: releases
  api_key:
    secure: YmlDBMXPa0xRB7J1IjJsYsCStLTW7tMtqGHhOo53/BufHHjFi7hG59AQzvdkc3rPhCc2WHJu/SjbfU1p63h8ytPclovMpfR5xs3p5Jz9VZh0VjPYuBypMCBiwzw7AoN0cqV23H4VQw4lULxTowmv2KqH3tQcPUjGBu110nri39PRqYJ56B57f5mPLF6W2r1A3Ul/IQAH10bGw50yxo/t5N8pFba14j5UoMs9Hr3X3V3w9yQIjxt2lTvAbW0XBCj6ZXWGXG5ne1bo48Z8Zu4O+ccA+1g5n5bhrlkysgkJHGkei+LhYLU9eq1MZOsiTCOQbwTH3JKuuvrLkbIngHhaodFqtWrLCXLOtSixeZbueUIm35G6LszBjLg3c1O4g0Oorj9BEm1r3oO2EDi484nyLft3skZdFKPvWywOTwNl/NnJTm+Efd1yvVhbPeRLdWH51HPlbwedPLzk3JcmtfsWAmhFzePTxNueN17Ty1lwveu0/cnn5hnNKm/g1Ksgg7PabI59BqEvzfTe8MqNJAH4p0K5Od5QeyyGajUPvv1mIeIE2z28ZIEDWNbzRXnrrbllFfaMxll3BQce83Yp3vSbUhhojA1uEUe22BfWUizVy65/tn5Lqe1XI44jTcJtdLtthd8C/jCArz+poIx4Nh0+EyG4CQGOyqvaPAYQoFSGzcY=
  file: "./documents/srs.pdf"
  skip_cleanup: true
  on:
    tags: true
