sudo: required
language: generic
services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic --keep-intermediates --reruns 0 srs.tex"
  
deploy:
  provider: releases
  #api_key:
  #  secure: 
  file:
  - ./documents/srs.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
