version: "2.1"
services:
    limesurvey:
        build: .
        container_name: limesurvey
        ports:
            - 80:80
        volumes:
            - ./LimeSurvey:/var/www/html/
        depends_on:
            - limesurvey_db
        networks:
            limesurvey_network: 
                ipv4_address: 10.5.0.5
    limesurvey_db:
        image: mysql:5.5.61
        container_name: limesurvey_db
        ports:
            - 4306:3306
        networks:
            limesurvey_network: 
                ipv4_address: 10.5.0.6
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data:/var/lib/mysql
networks:
    limesurvey_network:
        driver: bridge
        ipam:
          config:
            - subnet: 10.5.0.0/16
              gateway: 10.5.0.1
