---
swagger: "2.0"
info:
  description: "This is a simple API"
  version: "1.0.0"
  title: "Project Eval API"
  contact:
    email: "contact@teachingevaluations.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/teameval/Eval/1.0.0"
tags:
- name: "admins"
  description: "Operations available to administrators"
- name: "teachers"
  description: "Operations available to teachers"
schemes:
- "https"
paths:
  /courses:
    get:
      tags:
      - "teachers"
      - "admins"
      summary: "retreives a list of all courses"
      operationId: "courses_get"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        description: "the ID for a teacher/administrator"
        required: true
        type: "integer"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Course"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
  /course:
    get:
      tags:
      - "teachers"
      - "admins"
      summary: "retreives the info for a specific course"
      operationId: "course_get"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "the name for a course"
        required: true
        type: "integer"
      responses:
        200:
          description: "course info matching criteria"
          schema:
            $ref: "#/definitions/Course"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
    put:
      tags:
      - "teachers"
      - "admins"
      summary: "updates the info for a specified course"
      operationId: "course_put"
      parameters:
      - name: "name"
        in: "query"
        description: "the name for a course"
        required: true
        type: "integer"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
    delete:
      tags:
      - "teachers"
      - "admins"
      summary: "deletes a specified course"
      operationId: "course_delete"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "the name for a course"
        required: true
        type: "integer"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
  /new_course:
    post:
      tags:
      - "teachers"
      - "admins"
      summary: "creates a new course"
      operationId: "new_course_post"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "course"
        required: false
        schema:
          $ref: "#/definitions/course"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
definitions:
  Course:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "1"
      name:
        type: "string"
        example: "COS 397"
      addresses:
        type: "array"
        example:
        - "stanley.small@maine.edu"
        - "jovon.craig@maine.edu"
        items:
          type: "string"
    example:
      addresses:
      - "stanley.small@maine.edu"
      - "jovon.craig@maine.edu"
      name: "COS 397"
      id: "1"
  course:
    type: "object"
    properties:
      name:
        type: "string"
        example: "COS 397"
      copy:
        type: "boolean"
        description: "copy info from a course of the same name"
